apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: flaviobrusamolin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goserver-service
                port:
                  number: 80
  tls:
    - hosts:
        - flaviobrusamolin.com
      secretName: letsencrypt-tls
